[workspace]
members = [
    "drapto-core",
    "drapto-cli",
]
default-members = ["drapto-cli"] # Tells 'cargo run' to run the drapto-cli package by default
resolver = "2"

[profile.release]
lto = true
codegen-units = 1