name: CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libmediainfo-dev pkg-config
      
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      
      - run: cargo build --all